"""Initial migration

Revision ID: 05f6ab08087d
Revises: 365f7879fba6
Create Date: 2024-11-26 10:09:35.505416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f6ab08087d'
down_revision = '365f7879fba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.drop_column('month_year')
        batch_op.drop_column('sale_date')
        batch_op.drop_column('product_id')
        batch_op.drop_column('monthly_sale')
        batch_op.drop_column('temperature')
        batch_op.drop_column('product_profit')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_number', sa.String(length=15), nullable=False))
        batch_op.alter_column('profit',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_column('owner_name')
        batch_op.drop_column('gstNumber')
        batch_op.drop_column('business_email')

    with op.batch_alter_table('user_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_email', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gstNumber', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('owner_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('profit',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('gst_number')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('monthly_sale', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sale_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('month_year', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
