"""empty message

Revision ID: 0c9a542f81b4
Revises: 95e1273a7edc
Create Date: 2024-12-11 13:52:00.615781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9a542f81b4'
down_revision = '95e1273a7edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('selling_price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cost_price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_cost_price',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.alter_column('total_cost_price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cost_price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('selling_price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
