"""empty message

Revision ID: 70dd19ea2569
Revises: 4def910cbda1
Create Date: 2024-12-08 11:19:32.827669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70dd19ea2569'
down_revision = '4def910cbda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('cart')

    # ### end Alembic commands ###
