"""empty message

Revision ID: 8bb0e7053984
Revises: f40ea5b55ae3
Create Date: 2024-12-07 13:47:03.914786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb0e7053984'
down_revision = 'f40ea5b55ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint('transaction_item_transaction_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'transaction', ['transaction_id'], ['bill_number'])
        op.drop_column('product', 'created_at')
        op.drop_column('product', 'updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_item_transaction_id_fkey', 'transaction', ['transaction_id'], ['id'])
        batch_op.alter_column('transaction_item', 'transaction_id', type_=sa.Integer)
        op.add_column('product', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
        op.add_column('product', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###
