"""empty message

Revision ID: da932a9d5343
Revises: 88c92f007adc
Create Date: 2024-12-07 17:38:38.956209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da932a9d5343'
down_revision = '88c92f007adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('cost_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('selling_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('product_P_unique_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_product_P_unique_id'), ['P_unique_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('total_cost_price')
        batch_op.drop_column('total_selling_price')

    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.alter_column('selling_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('cost_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('total_cost_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('profit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('total_cost_price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('cost_price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('selling_price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_selling_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_cost_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))
        batch_op.drop_index(batch_op.f('ix_product_P_unique_id'))
        batch_op.create_unique_constraint('product_P_unique_id_key', ['P_unique_id'])
        batch_op.alter_column('selling_price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('cost_price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    op.create_table('sale',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sale_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quantity_sold', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='sale_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sale_pkey')
    )
    # ### end Alembic commands ###
