"""empty message

Revision ID: f40ea5b55ae3
Revises: c1927a802c0b
Create Date: 2024-12-07 13:43:53.810684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40ea5b55ae3'
down_revision = 'c1927a802c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_item_transaction_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'transaction', ['transaction_id'], ['bill_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_item_transaction_id_fkey', 'transaction', ['transaction_id'], ['id'])

    # ### end Alembic commands ###
